export type VehicleImage = {
  id: number;
  image_url: string;
  is_main?: boolean | null;
  is_cover?: boolean | null;
  sort_order?: number | null;
  label?: string | null;
  notes?: string | null;
};

export type Veiculo = {
  id: number;
  title: string;
  brand?: string | null;
  model?: string | null;
  year?: number | null;
  fipe_brand_code?: string | null;
  fipe_model_code?: string | null;
  fipe_year_code?: string | null;
  fipe_code?: string | null;
  fipe_reference_month?: string | null;
  license_plate?: string | null;
  version?: string | null;
  color?: string | null;
  fuel?: string | null;
  transmission?: string | null;
  mileage?: number | null;
  price?: number | string | null;
  fipe_price?: number | string | null;
  purchase_price?: number | string | null;
  acquisition_cost?: number | string | null;
  acquisition_source?: string | null;
  preparation_cost_estimate?: number | string | null;
  preparation_cost_actual?: number | string | null;
  documentation_cost?: number | string | null;
  transport_cost?: number | string | null;
  commission_cost?: number | string | null;
  other_costs?: number | string | null;
  price_strategy?: string | null;
  ad_description?: string | null;
  notes?: string | null;
  repair_notes?: string | null;
  preparation_items?: Array<{
    description?: string;
    estimated_cost?: number;
    actual_cost?: number;
    status?: string;
  }> | null;
  images?: VehicleImage[];
  ad_quality_score?: number | null;
  is_featured?: boolean | null;
  status?: string | null;
  documentation_status?: string | null;
  documentation_notes?: string | null;
  legal_restriction_status?: string | null;
  ad_status?: string | null;
  preparation_status?: string | null;
  created_at?: string;
};

export type CreateVeiculoPayload = {
  brand: string;
  model: string;
  year: number;
  fipe_brand_code?: string | null;
  fipe_model_code?: string | null;
  fipe_year_code?: string | null;
  fipe_code?: string | null;
  fipe_reference_month?: string | null;
  license_plate?: string | null;
  version?: string | null;
  color?: string | null;
  fuel?: string | null;
  transmission?: string | null;
  mileage?: number | null;
  price?: number | null;
  fipe_price?: number | null;
  status?: string;
  purchase_price?: number | null;
  acquisition_cost?: number | null;
  acquisition_source?: string | null;
  preparation_status?: string;
  preparation_cost_estimate?: number | null;
  preparation_cost_actual?: number | null;
  documentation_cost?: number | null;
  transport_cost?: number | null;
  commission_cost?: number | null;
  other_costs?: number | null;
  price_strategy?: string | null;
  ad_description?: string | null;
  notes?: string | null;
  repair_notes?: string | null;
  preparation_items?: Array<{
    description: string;
    estimated_cost?: number | null;
    actual_cost?: number | null;
    status?: string;
  }>;
  image_urls?: string[];
  documentation_status?: string;
  documentation_notes?: string | null;
  legal_restriction_status?: string;
  ad_status?: string;
  ad_quality_score?: number;
};
